### ISSUE TITLE
Larger modlists become unwieldy

### ISSUE THREAD

**Issue by EarlOfMagadan** [cyberrumor/ammo#16]
After installing 50 mods it becomes increasingly unwieldy to scroll through all of them, some kind of folder and/or search system would help immensely.

**Comment by cyberrumor** [comment]
I was actually brainstorming a solution to this last night. I was thinking of introducing a sort of container that would be collapsible, which could hold multiple mods or plugins. Reordering mods inside of the group would be possible, and reordering the group as a whole would be possible. Groups would have isolated conflict resolution before their conflict winners would be considered against the rest of the files. It would not be possible to nest groups, but it would be possible to rename them and move mods in/out of them.

Buuuut I kind of like your idea of a search. I could do some sort of fuzzy find to limit the output to your search query. Something along the lines of 

```
search <keyword> # limit output to mods/plugins matching case-insensitive keyword
# execute any number of arbitrary commands here
clear # remove search filter
```

I'll probably do both eventually. I think I will start with the search filter though, because it's the fastest way to solve your issue. Does that implementation of searching look intuitive to you?

**Comment by cyberrumor** [comment]
Do you need the ability to search for mods that contain a specific folder or filename? Almost missed that.

**Comment by EarlOfMagadan** [comment]
> Do you need the ability to search for mods that contain a specific folder or filename? Almost missed that.

Thinking about it, that would be great feature. Not what I was proposing but I love it.

**Comment by cyberrumor** [comment]
Fuzzy find added in commit dcfe7ebd475b1f480cdcf279a107de1d1d5e7687. Closing this, but I will open new issues for groups and filename search.
