### ISSUE TITLE
Crash on Self-Terminating Description Tags

### ISSUE THREAD

**Issue by Kajmany** [cyberrumor/ammo#38]
This seems like a silly thing to do, but a mod I was trying to install did it. A FallUI component at https://www.nexusmods.com/fallout4/mods/60580 has the attached FOMOD. Starting at line 111 there's a few of these `<description />` tags. This slips past the description-scraping logic because there _is_ a description tag, but there _isn't_ text.

Zipped because Github doesn't trust XML (should anyone?)
[ModuleConfig.zip](https://github.com/cyberrumor/ammo/files/13944197/ModuleConfig.zip)

I think I have a simple fix I hope to PR shortly.

**Comment by cyberrumor** [comment]
Crap, didn't mean to close this lol. I'm going to keep this ticket open to remind myself to write a test for _get_steps(). We'll want to concoct a ModuleConfig.xml that has self terminating elements on all optional pieces of data rather than just for description (assuming there's more optional data). Anyway, nice fix. Thanks for the PR!
