### ISSUE TITLE
confirm on delete

### ISSUE THREAD

**Issue by duran55** [cyberrumor/ammo#67]
It will be good if there is confirmation prompt before removing a mod. I accidentally removed a wrong mod by mistyping the mod index. Something like: are you sure followed by mod's name. Another workaround is to add a log file with all the actions (install, delete, etc.) performed, where someone can check what is removed last and to reinstall it manually.

**Comment by cyberrumor** [comment]
I've played around with making `delete` require confirmation, and it was exceedingly annoying in practice. I ended up drawing the line at only being able to delete visible components by `<index>` or `<all>` instead of requiring confirmation, and `all` was additionally restricted to only working on deactivated mods.

I share the experience that an accidental `delete <index>` leaves me wondering what I just removed. I think the log file is the best solution here.

I'll go ahead an expand the scope of this issue to `log all actions`. Don't really want to clutter the interface, so I'll probably slap a log in `~/.local/share/ammo/<game>/ammo.log`.

**Comment by duran55** [comment]
I agree, logging to file is better than cluttering the interface. Another idea in addition to the log file: Once delete command is executed print on screen what has been deleted. That way user can verify mod name is correct.

**Comment by cyberrumor** [comment]
There is a new `log` command which shows the contents of `~/.local/share/ammo/<game>/ammo.log`. The following events appear as info level logs in that file:

    - init
    - deleting components
    - moving components
    - committing changes to disk
    - renaming components

**Comment by duran55** [comment]
Thanks.
